### ISSUE TITLE
Follow Feature

### ISSUE THREAD

**Issue by jaithind** [Intro-to-SE-Spring-2020/NYUnited#2]
As an user, I want a follow feature which will allow me to receive notifications whenever another person makes a post. I also want an unfollow feature
@aqd14 

Details

- A follow button when a user is visiting another profile

- An unfollow button in place of the follow button if that profile is already being followed.

**Comment by aqd14** [comment]
@Intro-to-SE-Spring-2020/nyunited The main audience of the user stories for this project should be on **user**. You can paraphrase your user story as "As an user, I want to follow a person of interest so that I can be aware of his updates". Same for first user story #1 .

**Comment by aqd14** [comment]
I think the users should be able to view posts of others without following them.
